{{- if .Values.secrets.dockerRegistry.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.dockerRegistry.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerRegistry | toJson | b64enc }}
{{- end }}
