apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name  }}-docker-registry-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Values.secrets.dockerRegistry | toJson | b64enc }}
